# Davin 2021-02
#
# docker-compose run --rm http_study
# TAG=alpine docker-compose run --rm http_study
#
# https://docs.docker.com/compose/compose-file/compose-file-v3/
#
# curl https://www.davin.com/23-1 -vk
# curl https://www.davin.com/30-1 -k --tlsv1.2
# curl https://www.davin.com/30-1 -k --tls-max 1.2
# curl https://www.metroid.net:8443/30-1 -k

version: "3"   # 1.13+
#version: "2"    # 1.10+
services:
  http_study:
    image: "geniuscat/http_study:${TAG:-latest}"

    container_name: http_study

    ports:
      - 80:80
      - 8080:8080
      - 440:440
      - 441:441
      - 442:442
      - 443:443
      - 8443:8443

    working_dir: /root/http_study/www
#    network_mode: "docker_default"

    #command: /bin/bash
    #command : '/bin/bash -c "cd /root/http_study/www && ./run.sh start && /bin/bash"'
    command : /bin/bash -c "./run.sh start"
    extra_hosts:
      - "www.davin.com:127.0.0.1"
      - "www.metroid.net:127.0.0.1"
      - "origin.io:127.0.0.1"
