# chrono 2021-02
#
# docker-compose run --rm http_study

version: "3"   # 1.13+
#version: "2"    # 1.10+

services:

  http_study:

    image: chronolaw/http_study

    container_name: http_study

    ports:
      - 80:80
      - 8080:8080

    #command: /bin/bash
    command : '/bin/bash -c "cd /root/http_study/www && ./run.sh start && /bin/bash"'

    extra_hosts:
      - "www.chrono.com:127.0.0.1"
      - "www.metroid.net:127.0.0.1"
      - "origin.io:127.0.0.1"
